name: Deploy Vue CLI to GitHub Pages

on:
  push:
    branches:
      - main   # roda sempre que fizer push no main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Pega o repositório
      - name: Checkout
        uses: actions/checkout@v3

      # Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Instala dependências
      - name: Install dependencies
        run: npm install

      # Build Vue CLI (gera dist/)
      - name: Build
        run: npm run build

      # Faz deploy para gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
